# Evana – Paed Alembic config (single DB)

[alembic]
# Point to Flask-Migrate's folder
script_location = db_migrations
# Fallback URL (Flask/ENV will override at runtime)
sqlalchemy.url = sqlite:////home1/bambidental/apps/evana-paed/evana_paed.sqlite
# file_template = %%(rev)s_%%(slug)s
# revision_environment = false

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic,flask_migrate

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_flask_migrate]
level = INFO
handlers =
qualname = flask_migrate

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
